  name: 'Add review team'

  on:
    issue_comment:
      types: [created]

  jobs:
    label-pr:
      name: Label PR with review team
      if: >
        github.event.issue.pull_request
        && !contains(github.event.issue.labels.*.name, 'review-requested')
      runs-on: ubuntu-latest
      steps:
        - name: team-label
          uses: actions/github-script@v6
          with:
            script: |
              const teams = [
                '@conda-forge/staged-recipes',
                '@conda-forge/help-c-cpp',
                '@conda-forge/help-cdts',
                '@conda-forge/help-go',
                '@conda-forge/help-java',
                '@conda-forge/help-julia',
                '@conda-forge/help-nodejs',
                '@conda-forge/help-perl',
                '@conda-forge/help-python',
                '@conda-forge/help-python-c',
                '@conda-forge/help-r',
                '@conda-forge/help-ruby'
              ];
              for (const team of teams) {
                  let text = context.payload.comment.body;
                  let result = text.includes(team);
                  if (result) {
                      label = team.replace("@conda-forge/help-", "");
                      github.rest.issues.addLabels({
                          issue_number: context.issue.number,
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          labels: [label, 'review-requested']
                      })
                  }
              }
