  name: 'Add awaiting author label on comment from review'

  on:
    pull_request_target:
      types: [synchronize]
    pull_request_review:
      types: [submitted]
    pull_request_review_comment:
      types: [created]

  jobs:
    label-pr:
      name: Label PR
      if: >
        (github.event.sender.login != github.event.pull_request.user.login)
        && contains(github.event.pull_request.labels.*.name, 'review-requested')
        && !contains(github.event.pull_request.labels.*.name, 'Awaiting author contribution')
      runs-on: ubuntu-latest
      steps:
        - name: author-commented
          uses: actions/github-script@v6
          with:
            debug: true
            script: |
              // FIXME: Requesting team membership requires authentication/pemissions
              var reviewer_is_staged_recipes_member = true;
              github.rest.teams.getMembershipForUserInOrg({
                  org: 'conda-forge',
                  team_slug: 'staged-recipes',
                  username: '${{ github.event.sender.login }}'
              });
              if (reviewer_is_staged_recipes_member) {
                github.rest.issues.removeLabel({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: ['review-requested']
                });
                github.rest.issues.addLabels({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    labels: ['Awaiting author contribution']
                });
              }
