  name: 'Add awaiting author label on comment from review'

  on:
    issue_comment:
      types: [created]

  jobs:
    label-pr:
      name: Label PR
      if: github.event.sender.login != github.event.issue.user.login && contains(github.event.issue.labels.*.name, 'review-requested') && ${{ github.event.issue.pull_request }} && !contains(github.event.issue.labels.*.name, 'Awaiting author contribution')
      runs-on: ubuntu-latest
      steps:
        - name: author-commented
          uses: actions/github-script@v6
          with:
            debug: true
            script: |
              github.rest.teams.getMembershipForUserInOrg({
                  org: 'conda-forge',
                  team_slug: 'staged-recipes',
                  username: ${{ github.event.sender.login }}
              });
              github.rest.issues.removeLabel({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: ['review-requested']
              });
              github.rest.issues.addLabels({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: [label, 'Awaiting author contribution']
              });
