  name: 'Automated review labels (2/2)'

  on:
    workflow_run:
      workflows:
        - 'Automated review labels (1/2)'
      types:
        - requested

  jobs:

    remove-review-requested-label:
      name: 'When reviewed, remove review-requested label'
      if: >
        github.event.pull_request
        && (github.event.sender.login != github.event.pull_request.user.login)
        && contains(github.event.pull_request.labels.*.name, 'review-requested')
      runs-on: ubuntu-latest
      steps:
        - name: check-team-review
          id: check_team_review
          uses: actions/github-script@v6
          with:
            script: |
              const requestedReviewersPromise = github.rest.pulls.listRequestedReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
              });
              return requestedReviewersPromise.then( responses => {
                  const team_review_requests = responses.data.teams;
                  const user_review_requests = responses.data.users;
                  if (team_review_requests.length == 0 && user_review_requests.length == 0){
                    console.log("No more requested reviews.");
                    return true;
                  }
                  console.log("Reviews still pending.");
                  return false;
              });
        - name: add-labels
          if: >
            (steps.check_team_review.outputs.result == 'true')
          uses: actions/github-script@v6
          with:
            script: |
              github.rest.issues.addLabels({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: ['Awaiting author contribution']
              });
        - name: remove-labels
          if: >
            (steps.check_team_review.outputs.result == 'true')
            && contains(github.event.pull_request.labels.*.name, 'review-requested')
          uses: actions/github-script@v6
          with:
            script: |
              github.rest.issues.removeLabel({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: ['review-requested']
              });
