  name: 'Automated review labels'

  on:
    issue_comment:
      types: [created]
    pull_request_review:
      types: [submitted]
    pull_request_review_comment:
      types: [created]

  jobs:
    add-review-team-label:
      name: 'When pinged, label a PR with review team'
      if: >
        github.event.issue
        && github.event.issue.pull_request
        && !contains(github.event.issue.labels.*.name, 'review-requested')
      runs-on: ubuntu-latest
      steps:
        - name: check-teams
          id: check_teams
          uses: actions/github-script@v6
          with:
            debug: true
            script: |
              const teams = [
                '@conda-forge/staged-recipes',
                '@conda-forge/help-c-cpp',
                '@conda-forge/help-cdts',
                '@conda-forge/help-go',
                '@conda-forge/help-java',
                '@conda-forge/help-julia',
                '@conda-forge/help-nodejs',
                '@conda-forge/help-perl',
                '@conda-forge/help-python',
                '@conda-forge/help-python-c',
                '@conda-forge/help-r',
                '@conda-forge/help-ruby'
              ];
              let found_label = false;
              for (const team of teams) {
                  let text = context.payload.comment.body;
                  const regex = new RegExp(team + '[^\-]|' + team + '$');
                  let result = regex.test(text);
                  if (result) {
                      const slug = team.replace("@conda-forge/", "");
                      const label = slug.replace("help-", "");
                      found_label = true;
                      github.rest.issues.addLabels({
                          issue_number: context.issue.number,
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          labels: [label, 'review-requested']
                      });
                      github.rest.pulls.requestReviewers({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: context.issue.number,
                        team_reviewers: [slug],
                      });
                  }
              };
              return found_label
        - name: remove-labels
          if: >
            (steps.check_teams.outputs.result == 'true')
            && contains(github.event.issue.labels.*.name, 'Awaiting author contribution')
          uses: actions/github-script@v6
          with:
            script: |
              github.rest.issues.removeLabel({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: ['Awaiting author contribution']
              })


    remove-review-requested-label:
      name: 'When reviewed, remove review-requested label'
      if: >
        (
          github.event.issue
          && github.event.issue.pull_request
          && contains(github.event.issue.labels.*.name, 'review-requested')
        ) || (
          github.event.pull_request
          && contains(github.event.pull_request.labels.*.name, 'review-requested')
        )
      runs-on: ubuntu-latest
      steps:
        - name: check-membership
          id: check_membership
          uses: actions/github-script@v6
          with:
            debug: true
            script: |
              const labels_response = coctokit.rest.issues.listLabelsOnIssue({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
              });
              labels_response.then(function(result) {
                console.log(result);
              }
              const requested_reviewers_response = github.rest.pulls.listRequestedReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
              });
              requested_reviewers_response.then(function(result) {
                console.log(result);
                const slug = 'staged-recipes';
                // FIXME: Check if conda-forge specific teams are in list
                if (
                  result.status == 200
                  && result.data.teams.length == 0
                ){
                  // No team reviews requested, so we can swap labels.
                  return true;
                }
              });
              return false;
        - name: add-labels
          if: >
            (steps.check_membership.outputs.result == 'true')
          uses: actions/github-script@v6
          with:
            script: |
              github.rest.issues.addLabels({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: ['Awaiting author contribution']
              });
        - name: remove-labels
          if: >
            (steps.check_membership.outputs.result == 'true')
            && contains(github.event.issue.labels.*.name, 'review-requested')
          uses: actions/github-script@v6
          with:
            script: |
              github.rest.issues.removeLabel({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: ['review-requested']
              });
